server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/yukhnovets/Desktop/microservice_project/conf-service/src/main/resources/config/orderservice,
                           file:///Users/yukhnovets/Desktop/microservice_project/conf-service/src/main/resources/config/restaurantservice
