management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
